apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" . }}-users
type: Opaque
stringData:
  users.xml: |   # файл с данными пользователей
    <clickhouse>
      <users>
    {{- range .Values.users }}
        <user>
          <name>{{ .name }}</name>
          <password>{{ .password }}</password>
          <profile>{{ default "default" .profile }}</profile>
          <networks>
            <ip>::/0</ip>
          </networks>
        </user>
    {{- end }}
      </users>
    </clickhouse>
